import './globals.css'
import Navbar from './components/navbar/Navbar'
import { Nunito } from 'next/font/google'
import ClientOnly from './components/ClientOnly';
import RegisterModal from './components/modals/RegisterModal';

export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientOnly>
          <RegisterModal />
        <Navbar />
        </ClientOnly>
        {children}
        </body>
    </html>
  )
}
